### ISSUE TITLE
Width of outline and text buttons in header

### ISSUE THREAD

**Issue by tin2tin** [britalmeida/edit_breakdown#2]
Looks wonderful! 
![image](https://media.blenderartists.org/uploads/default/original/4X/4/4/8/448614f5214a241788f61e78bf06004780b2c6b0.gif)

Great work, I can see great potential in this. The thumbnail selection could maybe also be used for navigating when color grading or adding data to storyboards for printouts html/pdf. 

A small thing we struggled with, when we did the outlines in the sequencer, is that on MacOS, is one pixel width too narrow and the outline become invisible, and the only way to draw them visible is to draw two lines as outlines - doubling the line width doesn't work on Macs. 

William was very much against buttons in headers with text in them, and they have been removed everywhere in Blender. Maybe worth considering?

Looking forward to see where you guys are taking this.

**Comment by britalmeida** [comment]
Hi, thanks! Nice that it’s working out for you already :)

I’m trying to keep things generic enough so that the add-on could potentially be used in different workflows, from a contact sheet for lighting/grading, to a place to add feedback or for task management. I didn’t think of exporting printouts in html/pdf.

For the 1px outlines in macOS, I recall Clement investigated a similar issue for the 3D View. I’ll test it, and can switch from using lines to drawing a larger rect behind the thumbnails if needed.

Text in headers: I see the point, thanks for the suggestion. For now, the UI is still an experiment, but I’ll consider it in the future.

**Comment by tin2tin** [comment]
I once did a slideshow program which could output sheets storyboard sheets like this: http://download.videohelp.com/tin2tin/storyboard.html With all of your custom properties, a really useful custom info box could be added to the sheets.  At that time exporting to html seemed as simplest format containing images and text. Maybe there are some better formats out now. 

For inspiration, do you know about the VSE thumbnail patch: https://developer.blender.org/D5908
And this add-on which is for Project Management with color coding on the strips: https://github.com/samytichadou/blender_project_manager

Your tool seems to be very useful for project management too.

**Comment by britalmeida** [comment]
The **storyboard export** is a nice idea, but it's not my main focus right now, so I may never get to it.

Thanks for the links to related projects. I didn't know them yet.
**VSE thumbnail patch**: that would be really nice to have, and I believe the benefits are independent from a grid view of thumbnails. Having them directly in the sequencer is really nice for editing and having them in a grid, with no other visual noise, helps perceiving the overview differently.
I can imagine the grid view from this add-on being part of Blender's standard functionality (but not the custom properties). I would only propose making the grid as Blender core functionality after nailing the UI/UX in Python, as that's faster to iterate.
**Project Management**: I took a quick look, but there is no documentation or pictures, so I'd have to test it to see what it does. From looking at the code, I see some really bad practices, though.

**Comment by tin2tin** [comment]
No worries. I just keep guessing, what your main intent with this add-on is. ;-) There is also a thread on the Project Management add/on here: https://blenderartists.org/t/bpm-blender-project-manager/1223236 
Stuff like color coding shot version, made me think of your project: https://www.youtube.com/watch?v=c62RygIaJE8 But it is a very different project, since in includes tools for an integrated workflow of 3D View with the Sequencer.
