### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by tin2tin** [britalmeida/edit_breakdown#3]
I wanted to try your add on(after renaming the download of it), with this new add-on: https://gist.github.com/tin2tin/f2ecfc36a9faf90594d1246b11a1ab46 to detect and split a video into individual shots, however I got this error: 
![image](https://user-images.githubusercontent.com/1322593/104918287-d0520480-5994-11eb-90a9-9ef2327af645.png)

**Comment by britalmeida** [comment]
Hello!
What causes this to happen? Could it be that you've pressed sync and there are no markers in the edit?

Why did you have to rename the download of this add-on?

**Comment by tin2tin** [comment]
Yes, that's it. I forgot that it is based on markers. I remembered it as strip-based. Maybe an info report could tell users about it if no markers are found? A mode for extracting strip starts(movie, image, scene, color...), could maybe also be useful?

**Comment by britalmeida** [comment]
Fixed with commit d3dbe96138b82ca2efb828a7268081c1114f4867
