### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "edit_breakdown" not found'

### ISSUE THREAD

**Issue by DustinD-stack** [britalmeida/edit_breakdown#8]
Python: Traceback (most recent call last):
  File "C:\Users\inhis\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\edit_breakdown-master\ops\sync.py", line 113, in execute
    addon_prefs = bpy.context.preferences.addons['edit_breakdown'].preferences
KeyError: 'bpy_prop_collection[key]: key "edit_breakdown" not found'
![Screenshot (14)](https://user-images.githubusercontent.com/61642949/204197646-e43abd19-4975-47bf-a13c-eb42a4a2a24e.png)

**Comment by britalmeida** [comment]
Hello!
I can't think of what would cause this. The error is about not finding the add-on's settings, as if it is not enabled, but the screenshot clearly shows the add-on's UI.
Does this happen all the time? If so, can you:
- open the `Python Console` editor (in Blender, shows under `Text Editor`)
- paste `bpy.context.preferences.addons` and press `Tab`
That should show a list of enabled add-ons. Does it have `edit_breakdown`? Maybe the spelling isn't right?

**Comment by DustinD-stack** [comment]
hello Ines,

yeah it's there just not working..
thanks for responding

**Comment by tin2tin** [comment]
Read the first couple of lines here: https://github.com/britalmeida/edit_breakdown/issues/1#issuecomment-818556686

**Comment by britalmeida** [comment]
Closed as fixed with the commit above.
